### ISSUE TITLE
Cant wake-up washing machine in last version

### ISSUE THREAD

**Issue by dragonerix** [ollo69/ha-smartthinq-sensors#504]
Hi, in version 0.31.4 i cant wake-up my washing machine with "SmartThinQ LGE Sensors: WakeUp". But in version 0.31.3 was working fine. I need this for remote start. Thank you.

machine is LG F104J8JH2WD

**Comment by sorenbek** [comment]
I got the same problem with my RC90U2_WW-Dryer

**Comment by kpolders** [comment]
Same here: LG F4WV912A2E washer

**Comment by Xlinx64** [comment]
Same for me: V4WD860B

**Comment by dragonerix** [comment]
Please can you repair it? in last version 31.5 still not working...

**Comment by dragonerix** [comment]
@ollo69 pls

**Comment by ollo69** [comment]
Please attach diagnostic files when device is in a status that can be wake-up so that I can better understand how this should be managed.

**Comment by dragonerix** [comment]
> 

[config_entry-smartthinq_sensors-9a4817d7b3ae06e63e4122aa13055706.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11183545/config_entry-smartthinq_sensors-9a4817d7b3ae06e63e4122aa13055706.json.txt)

**Comment by dragonerix** [comment]
@ollo69 
Here is:
[config_entry-smartthinq_sensors-9a4817d7b3ae06e63e4122aa13055706.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11183566/config_entry-smartthinq_sensors-9a4817d7b3ae06e63e4122aa13055706.json.1.txt)

Remote start working fine until device is satandby... After standby is not possible wakeup od remote start. Thank you

**Comment by dragonerix** [comment]
> Please try last release and let me know if it fix the issue.

Working great!! Thank you so much.

**Comment by gabi1324** [comment]
Hi! I updated to the latest release and the wakeup service responds with "unknown error". It used to work in 0.31.4 and 0.31.5. Also, the power switch is broken since a few releases back. It doesn't do anything, it goes online when I turn on the washer, but when I try to turn it off from HA it goes unavailable for a few seconds and goes back to the previous state.

[config_entry-smartthinq_sensors-06a774f58ee56ffb645ea7e4f785c74f.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11208800/config_entry-smartthinq_sensors-06a774f58ee56ffb645ea7e4f785c74f.json.1.txt)
(the washer is off and I can use the wakeup service in version 0.31.5)

**Comment by ollo69** [comment]
Wake-up is my nightmare 😒. I'll check...

**Comment by mrombouts** [comment]
Hi, 
I have the same issue to wake up from stand-by with a dryer RC90V9_WW - using 0.31.6
It throws an API error - waking the dryer up from the LG app works just fine.

**Comment by mrombouts** [comment]
@ollo69 any update on this issue?
seems waking up those devices is not really straight forward...

**Comment by ollo69** [comment]
Please try if last release fix the issue (and hopefully do not break for other models).

**Comment by gabi1324** [comment]
Hi! Thank you for your work! The issue with my washing machine is solved and I can wake it up.
In the mean time, I discovered another problem with the wakeup service, this time with my dryer. I can't remember on what version it was working. Later I will post the diagnostic file and the last working version for my dryer.

**Comment by gabi1324** [comment]
I tried downloading version 0.31.4 and it doesn't work. I don't think I can find the last working version.

This is the diagnostic file on 0.31.8
[config_entry-smartthinq_sensors-06a774f58ee56ffb645ea7e4f785c74f.json (2).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11536168/config_entry-smartthinq_sensors-06a774f58ee56ffb645ea7e4f785c74f.json.2.txt)

**Comment by mrombouts** [comment]
Hi @ollo69 
When calling the service to wake up, I get a failure. Following is seen in the HA logs:

`websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 809, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 696, in async_wake_up
    await self._api.device.wake_up()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 249, in wake_up
    raise InvalidDeviceStatus()
custom_components.smartthinq_sensors.wideq.core_exceptions.InvalidDeviceStatus`

Any idea? 
Thanks,
Michiel

**Comment by gabi1324** [comment]
Still an issue.

**Comment by dragonerix** [comment]
Still not working in last and all other versions. Pls can you repait it? Thank you.

**Comment by sorenbek** [comment]
yes still an issue

**Comment by ollo69** [comment]
This issue is duplicated of #489 and should be fixed now. Generally speaking is not possible to turn on device if not in stand-by status waiting for remote start. `InvalidDeviceStatus` error is because device is not in expected status.

**Comment by mrombouts** [comment]
This is indeed working now.
Thanks a lot for all the efforts you do on this integration!
