### ISSUE TITLE
 not logged in error stalls integration

### ISSUE THREAD

**Issue by lars-t** [ollo69/ha-smartthinq-sensors#527]
**Describe the bug**
I use this integration mainly to set my aircos on/off.
Regularly this integration stops functioning. The log shows a NotLoggedInError.
The LG Thinq app has no problems when connecting with the same credentials.
This is unrecoverable and homassistant has to be restarted. A reset/reload off the integration itself does not work.

**Expected behavior**
Automatic recovery/retry after failure

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): docker 
 - Home Assistant version installed: 2023.4.2
 - Component version installed: v0.31.6
 - Last know working version:
 - LG device type and model with issue: RAC_056905_WW-RAC
 - LG devices connected (list):

**Output of HA logs**
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:349
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:32:51 (1 occurrences)
Last logged: 10:32:51

[140369613807936]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 282, in async_set_hvac_mode
    await self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 704, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 873, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 529, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 490, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1183, in device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1020, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 337, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 349, in _manage_lge_result
    raise API2_ERRORS[code](message)
custom_components.smartthinq_sensors.wideq.core_exceptions.NotLoggedInError

```

```

**Additional context**

**Comment by jofr666** [comment]
I have the same problem.

**Comment by jeffgoh** [comment]
me too - I think this is related to those people who said the integration works for a day or so.   Looks to be a time out, so if the integration detects not logged in, can it try to log in again so we don't need to restart @ollo69  ?

**Comment by ollo69** [comment]
I need to investigate more deeply this, but I'm really busy with m job in this period. I'll work on this and others issue / FR as soon as I will have some more additional time.

**Comment by bramstroker** [comment]
I also have the same problem. None of my airco units working anymore.
Thanks for looking into this @ollo69. Let me know if we can provide more debug information.

**Comment by ollo69** [comment]
Maybe I found the issue and fixed with last release. Please test and give me your feed-back.

**Comment by ollo69** [comment]
Fine, I close this issue.

**Comment by jeffgoh** [comment]
I'm on 0.31.8 using HACS inside a container running 2023.4.6 (newer images break my August lock) - just had to restart HA to get control of my aircons via HA.  Will get logs when it next happens

**Comment by jeffgoh** [comment]
@ollo69 still happens for me on HA 2023.4.6 + 0.31.8 (thinq)

Looks to be the same as @lars-t - what version(s) of everything are you running, @bramstroker ?

```
2023-06-01 18:40:35.336 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140073489756368] Not logged in.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 400, in async_turn_on
    await self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 704, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 873, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 528, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 479, in _set_control
    await self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1160, in set_device_controls
    res = await self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1013, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 346, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 372, in _manage_lge_result
    raise API2_ERRORS[code](message)
custom_components.smartthinq_sensors.wideq.core_exceptions.NotLoggedInError: Not logged in.

```
