### ISSUE TITLE
After a while the Integration starts failing to call Service until a restart.

### ISSUE THREAD

**Issue by BryceSoker** [ollo69/ha-smartthinq-sensors#539]
**Description**
I am using the integration mostly for HVAC systems.

From time to time (normally when I keep Home Assistant running without any restart for several days) the entire integrations seems to stop working. Each time I give it a command such as turning on/off, or changing the temperature/mode I receive the errors such as:

- Failed to call service climate/turn_on.
- Failed to call service climate/set_hvac_mode.

This only gets fixed after I restart HA.

Below I added a few logs i managed to catch, with some debug logs I added of my own.

**Environment details:**
 - Home Assistant version installed: 2023.4.6
 - Supervisor: 2023.04.1
 - Operating System: 10.1
 - Component version installed: v0.31.6

**Output of HA logs**
Paste the relavant output of the HA log here.

```
2023-05-10 16:30:30.607 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device a93ddab3-2b01-1826-a7cf-dc039850d386:  basicCtrl - Set - airState.operation - 257
2023-05-10 16:30:30.608 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/a93ddab3-2b01-1826-a7cf-dc039850d386/control-sync
2023-05-10 16:30:31.029 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0102', 'result': ''}
2023-05-10 16:30:31.032 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547538158976] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 400, in async_turn_on
    await self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 704, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 873, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 529, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 490, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1183, in device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1020, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 337, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 349, in _manage_lge_result
    raise API2_ERRORS[code](message)
```

**Comment by den-mac** [comment]
I don't know if I'm running into the same issue but for me the integration consistently fails after "some time" although trying to determine that timeframe is challenging. For me it's used exclusively for laundry related alerts, and I am seriously considering looking into other means of determining when cycles are done since this has been so flaky for me.

Basically I can fix things with an HA restart. I have never been able to reload the integration itself - it always gets stuck "initializing" and nothing happens.

On at least one occasion (last year) the integration was pending a password update so I went into the phone app (LG one) and updated my password. Then the integration started working again.

But these recent failures are frustrating because we don't do laundry very often and when we do that's when I find out the integration isn't connected.

I'm not that familiar with how to find debug logs, etc., but I did see where there is a place to turn on debug logging so I'll try that.

**Comment by BryceSoker** [comment]
> On at least one occasion (last year) the integration was pending a password update so I went into the phone app (LG one) and updated my password. Then the integration started working again.

Also had that happen to me. Not sure if related tho.

**Comment by ollo69** [comment]
Maybe I found the issue and fixed with last release. Please test and give me your feed-back.

**Comment by BryceSoker** [comment]
Will do, thank you.

**Comment by ollo69** [comment]
Based also on comment from similar issue seems that this problem is solved, so I close the issue. If problem persist please open a new one.

**Comment by den-mac** [comment]
Just a quick note - this is still failing for me so I'm giving up and removing it from HA and am going to try making my own solution to let me know when the washer & dryer are done. The actual LG phone app might be able to help me here. Sorry it didn't work out for me.

**Comment by ollo69** [comment]
> Just a quick note - this is still failing for me so I'm giving up and removing it from HA and am going to try making my own solution to let me know when the washer & dryer are done. The actual LG phone app might be able to help me here. Sorry it didn't work out for me.

I suggest to open a new issue and provide more details, as integration diagnostics and error logs. Looks like you have a different problem from the one fixed in last release, so it will be better analyze in on a separate thread.
