### ISSUE TITLE
LG washer remain time always 00:01:00

### ISSUE THREAD

**Issue by wb5xo** [ollo69/ha-smartthinq-sensors#544]
**Describe the bug**
The washer remaining time shows 00:01:00 while off, which always adds a minute to end time. This prevents a timer card from working correctly.

**Expected behavior**
The remaining time should end up as 00:00:00 so end time does not keep recalculating.

**Screenshots**
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/106778974/24e86305-91e6-4abb-a945-cd23607c7199)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed: 2023.5.3
 - Component version installed: latest
 - Last know working version: unknown
 - LG device type and model with issue: WM6500HWA
 - LG devices connected (list): washer, dryer, dishwasher

**Comment by danleongjy** [comment]
I encountered this behaviour this morning. I believe this is not an issue with the HACS components but with SmartThinQ, as the HACS components shows what the app shows, which is the timer indefinitely frozen at X minutes remaining. I shut down HA, then removed the washer from SmartThinq, turned off power at the main for 5min, then re-added the washer to SmartThinq. Upon HA restart, the issue was resolved. Perhaps it is due to wifi connectivity dropping off when the appliance is operating.

**Comment by MattL0** [comment]
A timer/or other idea should be incorporated into the component i guess. When it reach 1 min, than wait 1 minute to set it to 0 .

**Comment by wb5xo** [comment]
I shutoff home I'm still showing that the entity is on despite my washer being powered off. 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/106778974/743a65d5-4725-4164-8e24-c44c674fc5b5)
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/106778974/d18cbe76-5ab3-446c-a5cf-4f01294de671)

**Comment by ajma** [comment]
I'm running into this problem too

**Comment by catduckgnaf** [comment]
Me, as well.

**Comment by ollo69** [comment]
Please provide integration diagnostic when device is on this specific state / condition.

**Comment by wb5xo** [comment]
Here is the integration diagnostics. The washer and dryer are currently in the off state with 1 minute remaining.
[config_entry-smartthinq_sensors-6794801972bd4472b82081dcc1cbda49.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/12388888/config_entry-smartthinq_sensors-6794801972bd4472b82081dcc1cbda49.json.txt)

**Comment by ollo69** [comment]
Why did you close this?

**Comment by wb5xo** [comment]
Apologies for confusion, I'm not meaning to close issue. It keeps default to close when I add comment.

**Comment by wb5xo** [comment]
I just updated and everything looks good now. The timers are off when the devices are off.

**Comment by ollo69** [comment]
Close this issue as it seem fixed.
