### ISSUE TITLE
Broken after update to HA 2024.2.0

### ISSUE THREAD

**Issue by RobertoCravallo** [ollo69/ha-smartthinq-sensors#693]
**Describe the bug**
Integration does not load after todays HA update to 2024.2.0

**Expected behavior**

**Screenshots**
![08564dbde913062df56e941543b1d1abd2691ae3](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/771dab29-f3d7-488a-a1b3-83675c08bb99)

**Environment details:**
 - HA 2024.2.0 under PROXMOX
 - v0.37.2

**Output of HA logs**

**Additional context**
Worked fine up to the HA update

**Comment by ollo69** [comment]
Please check and provide error log

**Comment by RobertoCravallo** [comment]
Sorry, not very firm with the LOG thingy, this helpful?

[home-assistant_smartthinq_sensors_2024-02-08T08-40-38.299Z.log](https://github.com/ollo69/ha-smartthinq-sensors/files/14206416/home-assistant_smartthinq_sensors_2024-02-08T08-40-38.299Z.log)

**Comment by mbalug7** [comment]
I got the same problem.
HA 2024.2 docker
Ubuntu Server 22.04
Rollback to 2021.6 version has fixed my issue, so I don't have additional logs.

**Comment by RobertoCravallo** [comment]
Uninstalled LG and reinstalled. Getting this message.

![Settings – Home Assistant 2024-02-08 14-56-48](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/0aaa067f-973e-444d-9632-a25c48e0ecc4)

**Comment by ollo69** [comment]
Again, as I explain at the beginning of this thread this problem is related to outdated version of pip, not the integration. You need to fix this or the config flow will never start.

**Comment by RobertoCravallo** [comment]
I reverted to 2024.1.6 and all is well again...

So how do I update PIP?

**Comment by ollo69** [comment]
Depend on the environment that you have. In the link that I provide there are the instruction for venv, I don't know which king of HA envirnoment you re using

**Comment by RobertoCravallo** [comment]
I am running HA in a PROXMOX VM.

**Comment by RobertoCravallo** [comment]
![2024 2: More voice, more icons, more integrations, more  everything! - Blog - Home Assistant Community 2024-02-08 15-44-02](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/f5e3c704-6a23-4643-a2f6-c1a2dee9d72f)

This is what HA moderator has to say about this.

**Comment by ollo69** [comment]
Ok, I will take a deeper look to the version of PYCountry used and if exist new version

**Comment by ollo69** [comment]
Think that I found the issue. Is new versions of `PyCountry` library that fail to install with Python 3.12. I have fixed this and will be available with next release.

**Comment by ollo69** [comment]
Please try last release, should work properly with Python 3.12 and HA 2024.2

**Comment by RobertoCravallo** [comment]
Hello [ollo69](https://github.com/ollo69), 
perfection, with your update of LG it is working now. My GARMIN integration was also not working, but after your fix, that is now working also. Thank you very much for your work.
Regards from Germany,
Robert

**Comment by ollo69** [comment]
> My GARMIN integration was also not working, but after your fix, that is now working also

I do not exactly understand the relation, unless also that integration is using `PyCountry` (and so should implement same fix that I did).

I close this.

**Comment by mbalug7** [comment]
It works in HA docker container as well.  Tnx

**Comment by mbalug7** [comment]
> It works in HA docker container as well. Tnx

Initially it worked fine, but then I rebooted my server, and now I have this: 
```
2024-02-09 13:41:51.439 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.smartthinq_sensors.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/smartthinq_sensors/config_flow.py", line 9, in <module>
    from pycountry import countries as py_countries, languages as py_languages
  File "/usr/local/lib/python3.12/site-packages/pycountry/__init__.py", line 10, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
2024-02-09 13:41:51.441 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration smartthinq_sensors to set up smartthinq_sensors configuration entry: Exception importing custom_components.smartthinq_sensors.config_flow
```

**Comment by ollo69** [comment]
@mbalug7,

good to know that it works, but my suspect is that there is another integration that force installation of newer `pycountry` version that cause the problem, and so the result can be random.
If you will have again the issue, you could try to disable other custom integration to try to identify the one that is causing the problem.

**Comment by RobertoCravallo** [comment]
You where right, the problem is back as of today. I did not install or update anything, but still...

**Comment by ollo69** [comment]
> You where right, the problem is back as of today. I did not install or update anything, but still...

Because you said that my change also fix Garmin integration, you could try to disable that to see if it is the cause.

**Comment by RobertoCravallo** [comment]
I disabled GARMIN, no change. Uninstalled GARMIN, no change. For me, LGE-Sensors is still not working...

**Comment by ollo69** [comment]
Try disabling also other integration, quite sure that this is not an issue on this integration.
Eventually, if you can open a terminal on your HA server, try to run the command `pip show pycountry` and report here the returned values.

**Comment by RobertoCravallo** [comment]
![Terminal – Home Assistant 2024-02-11 17-20-19](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/74bfbe74-bbcf-459d-8b6f-78068d44e352)

**Comment by ollo69** [comment]
Uhm, quite strange that pycountry is not installed at all. And if you install it with command `pip install pycountry<23.0.0,>=22.1.10` and that reboot HA? This could solve the issue...

**Comment by RobertoCravallo** [comment]
![Terminal – Home Assistant 2024-02-11 17-32-25](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/2c9d45bc-3ead-4983-ae45-38203c07e9e5)
Guess I am doing something wrong. I am using the HA TERMINAL.

**Comment by ollo69** [comment]
`pip install pycountry"<23.0.0,>=22.1.10"`

**Comment by RobertoCravallo** [comment]
That worked...  
![Terminal – Home Assistant 2024-02-11 17-46-12](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/4109919b-858f-4e29-93e4-5ad40197a2de)
Rebooted HA, noc hange. Reinstalled SmartThinQ LGE Sensors, no change.

**Comment by ollo69** [comment]
Uhm, I suspect that HA is running inside a `venv`, so you are not installing in the right place. You must understand how to activate the correct venv and perform the same check inside it.

**Comment by RobertoCravallo** [comment]
HA is running in a PROXMOX VM. I'm an old guy (68) and am just a user. I guess I will just wait and see what happens. I am very surprised, that there are not more people that have this problem.

**Comment by mbalug7** [comment]
I executed the following commands inside my HA docker container: [https://stackoverflow.com/a/77364602](https://stackoverflow.com/a/77364602)

Now it works after every reboot. Since I have dockerized version of Home Assistant, I would expect that all changes I make in the Docker container disappear after a restart, but for some reason it works. 

Currently, I really don't have time to delve deeper into this, but after I implemented the suggestions provided in the Stack Overflow answer, things started working correctly.

**Comment by RobertoCravallo** [comment]
.. unfortunately, my knowledge is nowhere close to even try to implement this!!!

**Comment by mbalug7** [comment]
> .. unfortunately, my knowledge is nowhere close to even try to implement this!!!

try to run these commands in terminal here:
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/37574078/c1aa5e67-56dc-43bf-be32-86c336ffb9b2)

**Comment by RobertoCravallo** [comment]
That is my screenshot... Did not work.

**Comment by mbalug7** [comment]
> That is my screenshot... Did not work.

yes, I just used is as a reference to show where to run the commands from stack overflow answer. 
Have you tried to reboot?
As I said, I don't know why it works now for me, but it just does. 
Also, I think I reinstalled this integration as a last step before reboot.

**Comment by ollo69** [comment]
Sorry but I really have no idea on what could be the problem. I have Python 3.12 and HA 2024.2.1 and everything work properly.

@RobertoCravallo,

are you sure that the problem is the same reported at beginning of this thread? As last option you could try to install the native component `Radio Browser` that should force installation of right version of `pycountry`

**Comment by ollo69** [comment]
I reopen this issue, let's see if others have same issue.

**Comment by upthinkweb** [comment]
Have the same issue. Running on HASSOS/VM on TrueNAS Scale.

**Comment by RobertoCravallo** [comment]
![Settings – Home Assistant 2024-02-12 07-14-55](https://github.com/ollo69/ha-smartthinq-sensors/assets/112649622/f6671575-04e3-45c2-986d-5681ebccf542)

Maybe mine whole HA is broken somehow!!

**Comment by RobertoCravallo** [comment]
Very, very strange. I installed HA on PROXMOX and then installed my back-up. After all was said and done, the error is gone. After restarting HA, it is back.... I am going crazy!!!!

**Comment by countrock** [comment]
Mine was broken! But it's fixed now by itself! Not sure what fixed it!

**Comment by RobertoCravallo** [comment]
I have a integration that is called TANKERKÖNIG (checks gasoline prices) which gives me a "internal server 500 error" most of the day. In the morning, it works just fine. Still have not figured out why this is so. Maybe it does not like a HA restart / boot?

I am hoping, just as it happened for [countrock](https://github.com/countrock), that it will go away by itself at some point...

**Comment by RobertoCravallo** [comment]
With todays update to 2024.2.2 it is working again...

**Comment by ollo69** [comment]
So at the end was not integration issue.😉.
I suppose that some library used by HA was causing the issue and in last update this has been fixed.
I close this, hoping that this issue do not come back again.

**Comment by RobertoCravallo** [comment]
Just wanted to let you know, that I found the problem and it was SOLARFOCUS. 

This is what I wrote the developer:
"I just installed a new HA VM under PROXMOX. From my running system I deinstalled SOLARFOCUS and made a back-up. Installed the back-up in the new VM HA and everything is fine. So I am very sure the problem lies with SOLARFOCUS."

**Comment by ollo69** [comment]
@RobertoCravallo ,

good catch! 
May be this should also be sent to the attention of HA team. They should not allow to break some functionality (included native integration) due to a custom integration.

**Comment by FreyrPL** [comment]
Hi,
With core update 2024.2.4 everything is back to normal. Addon works as it should ;)

**Comment by pcartwright81** [comment]
Updated to 2024.4.0.dev20240319 and the issue is back.  I'm using Home Assistant Operating System 12.2.dev20240313. 
I have tried the following:
Reinstalled Smarthinq Sensors
Installing Radio Browser
From the logs 2024-03-19 23:07:27.676 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package pycountry<23.0.0,>=22.1.10: ERROR: Cannot install pycountry<23.0.0 and >=22.1.10 because these package versions have conflicting dependencies.

Looking at the screenshots above, wouldn't we need to be inside of the docker container that core is running in to install pycountry?

**Comment by FreyrPL** [comment]
Problem is back. The thing is, after updating HA core to next version problem is gone untill HA restart. After restart problem is back untill next core update. Looks like some dependencies regarding 'pycountry ' are being reinstalled every restart. 
I have no clue how to resolve this.

**Comment by pcartwright81** [comment]
This is being tracked in issue 725.  I edited manifest.json at the location \\\homeassistant.local\config\homeassistant\custom_components\smartthinq_sensors to say pycountry>23.0.0 and it seems to be working now.  The version has to be greater than 23.0.0 for the new beta versions.

**Comment by nickrout** [comment]
Home assistant seems to have constrained pycountry to >23.12.11 two weeks ago. 

https://github.com/home-assistant/core/commit/f3984a9d3ee94b92fd5a1a8902532d436ca52353

This custom integration constrains pycountry to pycountry<23.0.0,>=22.1.10

You can't be >23.12.11 and <23.0.0. I suspect that is the problem.
